### ISSUE TITLE
Font references stored across frames

### ISSUE THREAD

**Issue by cschol** [fairplay/vcv-rack-plugins#2]
It looks like font references are stored across frames. This will crash the Rack VST.

```
src/plugin.hpp
163-
164-    FlatDisplay() {
165-            std::string fontPath = asset::plugin(pluginInstance, "res/fonts/MonoBold.ttf");
166:            font = APP->window->loadFont(fontPath);
167-    }
168-
169-    void step() override {
```

See [migration manual](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames) for more information on how to fix this.

**Comment by fairplay** [comment]
Fixed
